# Generated by Django 5.2.4 on 2025-07-29 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
