# Generated by Django 5.2.6 on 2025-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_managers_alter_customuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="roll_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
