# Generated by Django 5.2.4 on 2025-07-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0002_messfeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messfeedback",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="messfeedback",
            name="student",
        ),
        migrations.AddField(
            model_name="messfeedback",
            name="comments",
            field=models.TextField(default="No comment"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messfeedback",
            name="full_name",
            field=models.CharField(default="Anonymous", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messfeedback",
            name="roll_number",
            field=models.CharField(default="0000", max_length=20),
            preserve_default=False,
        ),
    ]
