# Generated by Django 5.2.6 on 2025-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0013_complaint_category_alter_complaint_room_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outpassrequest",
            name="roll_number",
        ),
        migrations.AlterField(
            model_name="outpassrequest",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
